### ISSUE TITLE
迷惑行为？

### ISSUE THREAD

**Issue by ouuan** [code004Accepted/GC-Server#1]
- 不开源
- 放 Github 上
- 有 [开源协议](https://github.com/code004Accepted/GC-Server/blob/master/LICENSE)
- 用百度云下载
- 没有项目介绍

**Comment by chuang-zhi** [comment]
# +1

@code004Accepted

**Comment by ouuan** [comment]
`<h1>` 不是拿来当 `<strong>` 用的（

**Comment by code004Accepted** [comment]
> * 不开源
> * 放 Github 上
> * 有 [开源协议](https://github.com/code004Accepted/GC-Server/blob/master/LICENSE)
> * 用百度云下载
> * 没有项目介绍

这确乎是迷惑行为了qwq

好像没有说放在Github上就要开源吧qwq 其实我只是用Pages功能

这个开源协议，是当初我不懂的时候瞎弄的，马上删除，感谢提醒

至于百度云，主要是为了方便大陆用户，最近的版本都把百度云的下载方式丢到最后了

这个项目介绍，建站的时候没时间写，就一直咕咕了qwq 感谢提醒，周末马上写

（问题多多啊qwqwq

**Comment by ouuan** [comment]
（不觉得百度云方便大陆用户（逃））

**Comment by JackMerryYoung** [comment]
呵呵
